package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * ClientPrc generated by hbm2java
 */
public class ClientPrc implements java.io.Serializable {

	private Integer idClient;
	private HistoCmd histoCmd;
	private String nom;
	private String prenom;
	private String adresse;
	private String telephone;
	private Date dateNaissance;

	public ClientPrc() {
	}

	public ClientPrc(HistoCmd histoCmd, String nom, String prenom, String adresse, String telephone,
			Date dateNaissance) {
		this.histoCmd = histoCmd;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.telephone = telephone;
		this.dateNaissance = dateNaissance;
	}

	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	public HistoCmd getHistoCmd() {
		return this.histoCmd;
	}

	public void setHistoCmd(HistoCmd histoCmd) {
		this.histoCmd = histoCmd;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

}
