package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;

/**
 * Commerciaux generated by hbm2java
 */
public class Commerciaux implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String genre;
	private BigDecimal commission;
	private String pays;

	public Commerciaux() {
	}

	public Commerciaux(String nom, String genre, String pays) {
		this.nom = nom;
		this.genre = genre;
		this.pays = pays;
	}

	public Commerciaux(String nom, String genre, BigDecimal commission, String pays) {
		this.nom = nom;
		this.genre = genre;
		this.commission = commission;
		this.pays = pays;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	public BigDecimal getCommission() {
		return this.commission;
	}

	public void setCommission(BigDecimal commission) {
		this.commission = commission;
	}

	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

}
