package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
public class Cours implements java.io.Serializable {

	private String codecours;
	private String libellecours;
	private short nbjours;
	private Set seminaires = new HashSet(0);

	public Cours() {
	}

	public Cours(String codecours, String libellecours, short nbjours) {
		this.codecours = codecours;
		this.libellecours = libellecours;
		this.nbjours = nbjours;
	}

	public Cours(String codecours, String libellecours, short nbjours, Set seminaires) {
		this.codecours = codecours;
		this.libellecours = libellecours;
		this.nbjours = nbjours;
		this.seminaires = seminaires;
	}

	public String getCodecours() {
		return this.codecours;
	}

	public void setCodecours(String codecours) {
		this.codecours = codecours;
	}

	public String getLibellecours() {
		return this.libellecours;
	}

	public void setLibellecours(String libellecours) {
		this.libellecours = libellecours;
	}

	public short getNbjours() {
		return this.nbjours;
	}

	public void setNbjours(short nbjours) {
		this.nbjours = nbjours;
	}

	public Set getSeminaires() {
		return this.seminaires;
	}

	public void setSeminaires(Set seminaires) {
		this.seminaires = seminaires;
	}

}
