package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Employe generated by hbm2java
 */
public class Employe implements java.io.Serializable {

	private int numemp;
	private Projet projet;
	private String nomemp;
	private String prenomemp;
	private String poste;
	private BigDecimal salaire;
	private BigDecimal prime;
	private Integer superieur;
	private Set inscrits = new HashSet(0);

	public Employe() {
	}

	public Employe(int numemp, String nomemp, String prenomemp, String poste, BigDecimal salaire) {
		this.numemp = numemp;
		this.nomemp = nomemp;
		this.prenomemp = prenomemp;
		this.poste = poste;
		this.salaire = salaire;
	}

	public Employe(int numemp, Projet projet, String nomemp, String prenomemp, String poste, BigDecimal salaire,
			BigDecimal prime, Integer superieur, Set inscrits) {
		this.numemp = numemp;
		this.projet = projet;
		this.nomemp = nomemp;
		this.prenomemp = prenomemp;
		this.poste = poste;
		this.salaire = salaire;
		this.prime = prime;
		this.superieur = superieur;
		this.inscrits = inscrits;
	}

	public int getNumemp() {
		return this.numemp;
	}

	public void setNumemp(int numemp) {
		this.numemp = numemp;
	}

	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	public String getNomemp() {
		return this.nomemp;
	}

	public void setNomemp(String nomemp) {
		this.nomemp = nomemp;
	}

	public String getPrenomemp() {
		return this.prenomemp;
	}

	public void setPrenomemp(String prenomemp) {
		this.prenomemp = prenomemp;
	}

	public String getPoste() {
		return this.poste;
	}

	public void setPoste(String poste) {
		this.poste = poste;
	}

	public BigDecimal getSalaire() {
		return this.salaire;
	}

	public void setSalaire(BigDecimal salaire) {
		this.salaire = salaire;
	}

	public BigDecimal getPrime() {
		return this.prime;
	}

	public void setPrime(BigDecimal prime) {
		this.prime = prime;
	}

	public Integer getSuperieur() {
		return this.superieur;
	}

	public void setSuperieur(Integer superieur) {
		this.superieur = superieur;
	}

	public Set getInscrits() {
		return this.inscrits;
	}

	public void setInscrits(Set inscrits) {
		this.inscrits = inscrits;
	}

}
