package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HistoCmd generated by hbm2java
 */
public class HistoCmd implements java.io.Serializable {

	private Integer numCommande;
	private Date dateCmd;
	private Integer numFacture;
	private BigDecimal montantht;
	private String etatCommande;
	private Set clientPrcs = new HashSet(0);

	public HistoCmd() {
	}

	public HistoCmd(Date dateCmd, Integer numFacture, BigDecimal montantht, String etatCommande, Set clientPrcs) {
		this.dateCmd = dateCmd;
		this.numFacture = numFacture;
		this.montantht = montantht;
		this.etatCommande = etatCommande;
		this.clientPrcs = clientPrcs;
	}

	public Integer getNumCommande() {
		return this.numCommande;
	}

	public void setNumCommande(Integer numCommande) {
		this.numCommande = numCommande;
	}

	public Date getDateCmd() {
		return this.dateCmd;
	}

	public void setDateCmd(Date dateCmd) {
		this.dateCmd = dateCmd;
	}

	public Integer getNumFacture() {
		return this.numFacture;
	}

	public void setNumFacture(Integer numFacture) {
		this.numFacture = numFacture;
	}

	public BigDecimal getMontantht() {
		return this.montantht;
	}

	public void setMontantht(BigDecimal montantht) {
		this.montantht = montantht;
	}

	public String getEtatCommande() {
		return this.etatCommande;
	}

	public void setEtatCommande(String etatCommande) {
		this.etatCommande = etatCommande;
	}

	public Set getClientPrcs() {
		return this.clientPrcs;
	}

	public void setClientPrcs(Set clientPrcs) {
		this.clientPrcs = clientPrcs;
	}

}
