package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

/**
 * InscritId generated by hbm2java
 */
public class InscritId implements java.io.Serializable {

	private String codesemi;
	private int numemp;

	public InscritId() {
	}

	public InscritId(String codesemi, int numemp) {
		this.codesemi = codesemi;
		this.numemp = numemp;
	}

	public String getCodesemi() {
		return this.codesemi;
	}

	public void setCodesemi(String codesemi) {
		this.codesemi = codesemi;
	}

	public int getNumemp() {
		return this.numemp;
	}

	public void setNumemp(int numemp) {
		this.numemp = numemp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InscritId))
			return false;
		InscritId castOther = (InscritId) other;

		return ((this.getCodesemi() == castOther.getCodesemi()) || (this.getCodesemi() != null
				&& castOther.getCodesemi() != null && this.getCodesemi().equals(castOther.getCodesemi())))
				&& (this.getNumemp() == castOther.getNumemp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodesemi() == null ? 0 : this.getCodesemi().hashCode());
		result = 37 * result + this.getNumemp();
		return result;
	}

}
