package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

/**
 * ParticiperId generated by hbm2java
 */
public class ParticiperId implements java.io.Serializable {

	private int numemp;
	private String codesemi;
	private String codejour;

	public ParticiperId() {
	}

	public ParticiperId(int numemp, String codesemi, String codejour) {
		this.numemp = numemp;
		this.codesemi = codesemi;
		this.codejour = codejour;
	}

	public int getNumemp() {
		return this.numemp;
	}

	public void setNumemp(int numemp) {
		this.numemp = numemp;
	}

	public String getCodesemi() {
		return this.codesemi;
	}

	public void setCodesemi(String codesemi) {
		this.codesemi = codesemi;
	}

	public String getCodejour() {
		return this.codejour;
	}

	public void setCodejour(String codejour) {
		this.codejour = codejour;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParticiperId))
			return false;
		ParticiperId castOther = (ParticiperId) other;

		return (this.getNumemp() == castOther.getNumemp())
				&& ((this.getCodesemi() == castOther.getCodesemi()) || (this.getCodesemi() != null
						&& castOther.getCodesemi() != null && this.getCodesemi().equals(castOther.getCodesemi())))
				&& ((this.getCodejour() == castOther.getCodejour()) || (this.getCodejour() != null
						&& castOther.getCodejour() != null && this.getCodejour().equals(castOther.getCodejour())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumemp();
		result = 37 * result + (getCodesemi() == null ? 0 : this.getCodesemi().hashCode());
		result = 37 * result + (getCodejour() == null ? 0 : this.getCodejour().hashCode());
		return result;
	}

}
