package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

/**
 * PrimeReleve generated by hbm2java
 */
public class PrimeReleve implements java.io.Serializable {

	private PrimeReleveId id;

	public PrimeReleve() {
	}

	public PrimeReleve(PrimeReleveId id) {
		this.id = id;
	}

	public PrimeReleveId getId() {
		return this.id;
	}

	public void setId(PrimeReleveId id) {
		this.id = id;
	}

}
