package model;
// Generated 29 nov. 2018 15:47:49 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projet generated by hbm2java
 */
public class Projet implements java.io.Serializable {

	private String codeprojet;
	private String nomprojet;
	private Date debutproj;
	private Date finprevue;
	private String nomcontact;
	private Set employes = new HashSet(0);

	public Projet() {
	}

	public Projet(String codeprojet, String nomprojet, Date debutproj, Date finprevue, String nomcontact) {
		this.codeprojet = codeprojet;
		this.nomprojet = nomprojet;
		this.debutproj = debutproj;
		this.finprevue = finprevue;
		this.nomcontact = nomcontact;
	}

	public Projet(String codeprojet, String nomprojet, Date debutproj, Date finprevue, String nomcontact,
			Set employes) {
		this.codeprojet = codeprojet;
		this.nomprojet = nomprojet;
		this.debutproj = debutproj;
		this.finprevue = finprevue;
		this.nomcontact = nomcontact;
		this.employes = employes;
	}

	public String getCodeprojet() {
		return this.codeprojet;
	}

	public void setCodeprojet(String codeprojet) {
		this.codeprojet = codeprojet;
	}

	public String getNomprojet() {
		return this.nomprojet;
	}

	public void setNomprojet(String nomprojet) {
		this.nomprojet = nomprojet;
	}

	public Date getDebutproj() {
		return this.debutproj;
	}

	public void setDebutproj(Date debutproj) {
		this.debutproj = debutproj;
	}

	public Date getFinprevue() {
		return this.finprevue;
	}

	public void setFinprevue(Date finprevue) {
		this.finprevue = finprevue;
	}

	public String getNomcontact() {
		return this.nomcontact;
	}

	public void setNomcontact(String nomcontact) {
		this.nomcontact = nomcontact;
	}

	public Set getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set employes) {
		this.employes = employes;
	}

}
